# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bd16c190fdd6706c5e494c5ceccf235b0d9ad813358a30cc7ae939018ca22026abaf77f9501e72323fecdad58e5d0eebc8ef8b70cb31fc8d0bd4c197cbde532

test:
  secret_key_base: 9534c4952ef67959533c1104ca3e10140ca8339882d91d998f027ca3454c6cc0398e6ebf9707d75e2ed24d079efd2d2202353de6cc100b7c5e7ea2931bea5f4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
